YourAnimeList/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using YourAnimeList.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace YourAnimeList.Controllers
{
    [Authorize(Roles = "Manager")]
    public class CMSController : Controller
    {
        private readonly ILogger<CMSController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnviroment;

        public CMSController(ILogger<CMSController> logger, ApplicationDbContext context, IWebHostEnvironment hostEnviroment)
        {
            _logger = logger;
            _context = context;
            this._hostEnviroment = hostEnviroment;
        }

        public IActionResult AddAnime()
        {
            List<Anime> model = _context.Animes.ToList();

            return View(model);
        }

        //GET 
        public IActionResult CreateAnime()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnimeAsync(Anime obj)
        {
            if(ModelState.IsValid)
            {
                string wwwRootPath = _hostEnviroment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(obj.ImageFile.FileName);
                string extension = Path.GetExtension(obj.ImageFile.FileName);
                obj.AnimeURL = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;

                string path = Path.Combine(wwwRootPath + "/images/", fileName);
                using (var fileStram = new FileStream(path, FileMode.Create))
                {
                    await obj.ImageFile.CopyToAsync(fileStram);
                }


                _context.Animes.Add(obj);
                _context.SaveChanges();
                return RedirectToAction("AddAnime");
            }

            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _context.Animes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Anime obj)
        {
            if (ModelState.IsValid)
            {
                _context.Animes.Update(obj);
                _context.SaveChanges();
                return RedirectToAction("AddAnime");
            }

            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _context.Animes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {

            var obj = _context.Animes.Find(id);

            if(obj == null)
            {
                return NotFound();
            }
                _context.Animes.Remove(obj);
                _context.SaveChanges();
                return RedirectToAction("AddAnime");
        }
    }
}

YourAnimeList/Views/CMS/AddAnime.cshtml
@model IEnumerable<Anime>

@{
    ViewData["Title"] = "Anime Lists";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="add-title">Anime List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="CMS" asp-action="CreateAnime" class="btn btn-secondary">Add New Anime</a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Genere
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="15%">@obj.AnimeName</td>
                        <td width="10%">@obj.AnimeGenere</td>
                        <td width="65%">@obj.AnimeDescription</td>
                        <td class="text-center">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="CMS" asp-route-ID="@obj.ID" asp-action="Edit" class="btn btn-info mx-2 fa fa-pencil-square">Edit</a>
                                <a asp-controller="CMS" asp-route-ID="@obj.ID" asp-action="Delete" class="btn btn-danger fa fa-trash">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    else
    {
        <p>No item found.</p>
    }

</div>

YourAnimeList/Views/CMS/CreateAnime.cshtml
@model Anime


@{
    ViewData["Title"] = "Add New Anime";
}

<form method="post" asp-action="CreateAnime" enctype="multipart/form-data">

    <div class="border p-3 edit-bg">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Anime</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeName" class="form-control" />
                        <span asp-validation-for="AnimeName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeGenere"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeGenere" class="form-control" />
                        <span asp-validation-for="AnimeGenere" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeDescription"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeDescription" class="form-control" />
                        <span asp-validation-for="AnimeDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeReleaseDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeReleaseDate" class="form-control" />
                        <span asp-validation-for="AnimeReleaseDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeStudio"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeStudio" class="form-control" />
                        <span asp-validation-for="AnimeStudio" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeEpisodes"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeEpisodes" class="form-control" />
                        <span asp-validation-for="AnimeEpisodes" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeRating"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeRating" class="form-control" />
                        <span asp-validation-for="AnimeRating" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeURL"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeURL" class="form-control" />
                        <span asp-validation-for="AnimeURL" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ImageFile"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ImageFile" type="file" accept="image/jpg"/>
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div>
                            <a asp-action="AddAnime" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</form>

YourAnimeList/Views/CMS/Delete.cshtml
@model Anime

@{
    ViewData["Title"] = "Remove Anime";
}

<form method="post" asp-action="DeletePost">
    <input asp-for="ID" hidden />
    <div class="border p-3 edit-bg">

        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Anime</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeName" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeGenere"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeGenere" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeDescription"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeDescription" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeReleaseDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeReleaseDate" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeStudio"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeStudio" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeEpisodes"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeEpisodes" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeRating"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeRating" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeURL"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeURL" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div>
                            <a asp-action="AddAnime" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</form>

YourAnimeList/Views/CMS/Edit.cshtml
@model Anime

@{
    ViewData["Title"] = "Update Anime";
}

<form method="post">
    <input asp-for="ID" hidden />
    <div class="border p-3 edit-bg ">

        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Anime</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeName" class="form-control" />
                        <span asp-validation-for="AnimeName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeGenere"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeGenere" class="form-control" />
                        <span asp-validation-for="AnimeGenere" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeDescription"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeDescription" class="form-control" />
                        <span asp-validation-for="AnimeDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeReleaseDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeReleaseDate" class="form-control" />
                        <span asp-validation-for="AnimeReleaseDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeStudio"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeStudio" class="form-control" />
                        <span asp-validation-for="AnimeStudio" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeEpisodes"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeEpisodes" class="form-control" />
                        <span asp-validation-for="AnimeEpisodes" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeRating"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeRating" class="form-control" />
                        <span asp-validation-for="AnimeRating" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="AnimeURL"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="AnimeURL" class="form-control" />
                        <span asp-validation-for="AnimeURL" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div>
                            <a asp-action="AddAnime" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</form>